apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: terraria
spec:
  serviceName: terraria
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        terraria: "true"
      containers:
        - name: terraria
          tty: true
          stdin: true
          image: ryshe/terraria:vanilla-1.4.5.2
          ports:
            - containerPort: 7777
          env:
            - name: WORLD_FILENAME
              value: "Erathia.wld"
            - name: MAX_PLAYERS
              value: "8"
          volumeMounts:
            - name: terraria-data
              mountPath: /root/.local/share/Terraria/Worlds
      volumes:
        - name: terraria-data
          persistentVolumeClaim:
            claimName: terraria-pvc