apiVersion: v1
kind: Service
metadata:
  name: terraria
spec:
  type: LoadBalancer
  selector:
    app: terraria
  ports:
    - name: terraria
      port: 7777
      targetPort: 7777
      protocol: TCP