apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraria-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: terraria-local
  hostPath:
    path: /data/terraria